### ISSUE TITLE
Can't fork, can't push

### ISSUE THREAD

**Issue by maxim-belkin** [maxim-belkin/homebrew-xorg#1]
I can't fork this repo (because it is empty) and therefore can't create a PR.
I can't push to this repo because of permissions.
My repo is: https://github.com/maxim-belkin/homebrew-xorg

**Comment by sjackman** [comment]
Nice, Maxim! I'm at a conference today, and I'll look at this on Monday. Thanks, again!

**Comment by sjackman** [comment]
I've added you as a collaborator, Maxim. Go ahead and push yourself. Please add a README.md and copy LICENSE Linuxbrew.
