### ISSUE TITLE
origin/master pointer

### ISSUE THREAD

**Issue by maxim-belkin** [maxim-belkin/homebrew-xorg#10]
In my local repo I see `origin/master` pointer at `fba5478` (`git log --decorate --oneline --graph`) and it does not move when I or Bob commit to the repo. The actual content is updated but I'm just concerned seeing it at the same position.

**Comment by bw-yuhogg** [comment]
The given command seems to work fine for me.

At first I assumed that `origin` was pointing at your fork rather than the canonical repo, but I just checked and your fork is also up to date, so I'm at a loss.

**Comment by maxim-belkin** [comment]
Does it move with your / my commits for you?

**Comment by bw-yuhogg** [comment]
Yes. For example, right now:

> - 106a1c0 (HEAD -> master, origin/master, origin/HEAD, fix-xtrans-patch) xorg: correct installation message

Which is the last commit I did.

**Comment by maxim-belkin** [comment]
Looks like I no longer have this problem, so I'm closing this.
Not sure what was happening there.
