### ISSUE TITLE
Empty bottles

### ISSUE THREAD

**Issue by maxim-belkin** [maxim-belkin/homebrew-xorg#192]
The formulas listed below install most/all of their files into `font-utils`'s directories and, as a result, their bottles are empty. Fix their installation scripts and regenerate bottles or remove bottles.
- [x] encodings
- [ ] font-adobe-100dpi
- [ ] font-adobe-75dpi
- [ ] font-adobe-utopia-100dpi
- [ ] font-adobe-utopia-75dpi
- [ ] font-adobe-utopia-type1
- [ ] font-arabic-misc
- [ ] font-bh-100dpi
- [ ] font-bh-75dpi
- [ ] font-bh-lucidatypewriter-100dpi
- [ ] font-bh-lucidatypewriter-75dpi
- [ ] font-bh-ttf
- [ ] font-bh-type1
- [ ] font-bitstream-100dpi
- [ ] font-bitstream-75dpi
- [ ] font-cronyx-cyrillic
- [ ] font-cursor-misc
- [ ] font-daewoo-misc
- [ ] font-dec-misc
- [ ] font-ibm-type1
- [ ] font-isas-misc
- [ ] font-jis-misc
- [ ] font-micro-misc
- [ ] font-misc-cyrillic
- [ ] font-misc-ethiopic
- [ ] font-misc-meltho
- [ ] font-misc-misc
- [ ] font-mutt-misc
- [ ] font-schumacher-misc
- [ ] font-screen-cyrillic
- [ ] font-sony-misc
- [ ] font-sun-misc
- [ ] font-winitzki-cyrillic
- [ ] font-xfree86-type1

**Comment by bw-yuhogg** [comment]
We can fix this really quickly by deleting all of these bottles and adding `bottle :unneeded` to each of these formulae.

That said, I think this indicates a problem with bottling. If files installed into directories outside of the formula's Cellar prefix aren't included when installing from bottles, then all sorts of formulae will have different (and wrong) behaviour when poured from a bottle.

Are you aware of any core formulae with the same problem?

**Comment by maxim-belkin** [comment]
These formulas can be fixed by adding `--with-fontrootdir=#{share}/fonts/X11`.
We just need to make sure that it will behave the same way as it does when placed inside the font-util directory.

We could place symlinks into font-utils directory, but then, again, will bottle include these symlinks? Or, can we add them after pouring a bottle?

**Comment by bw-yuhogg** [comment]
One other option (that I'll admit makes me queasy) would be to stuff all of these formulae into resources for the `font-util` package, perhaps hidden behind a default-enabled option.

**Comment by maxim-belkin** [comment]
that might be not a bad idea. have to think about it.

**Comment by maxim-belkin** [comment]
The solution with `--with-fontrootdir=#{share}/fonts/X11` doesn't work in it's simplest implementation because of duplicate symlinks created by different formulas

**Comment by maxim-belkin** [comment]
I think for now we have to mark them as `bottle :unneeded` as modifying it so that homebrew detects new files in _other_ folders might take awhile.

**Comment by bw-yuhogg** [comment]
> I think for now we have to mark them as bottle :unneeded as modifying it so that homebrew detects new files in other folders might take awhile.

I'm okay with that plan. While there are a lot of fonts, none of them take all that long to build if I remember correctly.

Still, hopefully we come up with a better plan in the long term.

**Comment by maxim-belkin** [comment]
Reopening this until we have non-empty bottles

**Comment by maxim-belkin** [comment]
List of required font packages has been significantly [reduced](http://www.linuxfromscratch.org/blfs/view/svn/x/x7font.html)
```
  font-util-1.3.1.tar.bz2
  encodings-1.0.4.tar.bz2
  font-alias-1.0.3.tar.bz2
  font-adobe-utopia-type1-1.0.4.tar.bz2
  font-bh-ttf-1.0.3.tar.bz2
  font-bh-type1-1.0.3.tar.bz2
  font-ibm-type1-1.0.3.tar.bz2
  font-misc-ethiopic-1.0.3.tar.bz2
  font-xfree86-type1-1.0.4.tar.bz2
```
