### ISSUE TITLE
Configure flags, dependencies

### ISSUE THREAD

**Issue by maxim-belkin** [maxim-belkin/homebrew-xorg#2]
TODO:
Check if we need all the flags used by configure scripts and dependencies on `autoconf`.
In particular check if formulas need:
- `--disable-debug`
- `--disable-dependency-tracking`
- `--disable-silent-rules`
- `autoconf` dependency
- `pkg-config` dependency

<hr>

_[undone on March 14]_ Done ==> For all dynamic libraries run `ldd <library>` and check that emerging dependencies appear in the formula as "runtime" libraries.

``` bash
### in ./Library/Taps/linuxbrew/homebrew-xorg folder
for each in *.rb; do
    name=${each%.rb};
    unset a;
    echo -n "Formula: $name, ";
    a=($(brew list $name -v | grep "\.so$"));
    n=${#a[@]};
    echo "$n dependencies";
    for ai in ${a[@]}; do
       ldd $ai | grep -v -e "linux-vdso\.so\.1" -e "ld-linux-x86-64\.so\.2" -e "libc\.so\.6" -e "libdl\.so\.2" | awk '{print "    ",$1}';
    done | sort -u
done | tee deps.txt
```

<hr>

How to make the following kind of dependency?

``` ruby
# pseudo-code:
"depends_on "libxdmcp"  => :run if ! Formula["libxcb"].buildwithout?("libxdmcp")
```

**Comment by bw-yuhogg** [comment]
I'd be happy to help tomorrow with checking the formulae for excess `configure` flags.

**Comment by maxim-belkin** [comment]
That'd be great! Thanks! :)

**Comment by sjackman** [comment]
> `depends_on "libxdmcp"  => :run if ! Formula["libxcb"].buildwithout?("libxdmcp")`

There's no need to tag a dependency explicitly as `:run`. It's only used, as far as I know, to silence warnings about dependencies that are usually build time dependencies, like `cmake`, but for some particular formula is exceptionally also a run-time dependency.

Perhaps something like this? like here: https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Formula/python.rb#L34

``` ruby
depends_on "libxdmcp"  => if Tab.for_name("libxcb").with?("libxdmcp")
```

I don't think you want to list these recursive dependencies typically though. Just list

``` ruby
depends_on "libxcb"
```

and then in `libxcb.rb`

``` ruby
depends_on "libxdmcp" => :recommended
```

Also instead of using `ldd` to list the dependencies, which lists recursive dependencies as well, you can use `patchelf --print-needed` to list only the direct dependencies.

**Comment by maxim-belkin** [comment]
I will have to build `xorg` from scratch without `xdmcp` to check if dependency on `libxdmcp` appears because of `libxcb`.
I think it would be better to list dependencies caused by build flags of other formulas: this way formulas will be clear about their dependencies and be more consistent between each other.

**Comment by sjackman** [comment]
Only direct dependencies should be listed, not recursive dependencies. brew handles the recursive dependency expansion.

**Comment by sjackman** [comment]
You can list the recursive dependencies of a formula with `brew deps foo`.

**Comment by bw-yuhogg** [comment]
@maxim-belkin just to clarify - you want the extra `configure` flags _included_ if they work, right?

(I previously thought this issue was to take them out where they didn't work but after seeing that none of the formulae here include them, I suspect you meant the opposite).

**Comment by maxim-belkin** [comment]
I meant to include missing configure flags that homebrew usually uses for new formulas. I'm not sure they are necessary though.

**Comment by maxim-belkin** [comment]
Alright, I will remove all `:run` dependencies.

**Comment by maxim-belkin** [comment]
Note about `autoconf` dependency: right now there is a feature (read: bug) in `xmlto` package that it returns non-zero code when working on an empty file. Many packages use empty files to check if `xmlto` works and, as a result, think that it does not. I've added a patch (found on the internet) that fixes that. But as a downside we have to do "autoreconf" before configure and, hence, the `autoconf` dependency. So, we can remove that `autoconf` dependency once the packages fix the way they check if `xmlto` works or if `xmlto` reverts its behavior (which is doubtful).

**Comment by maxim-belkin** [comment]
I've changed the patch to patch the 'configure' script instead so we again no longer need the `autoconf` dependency. There was a weird problem (with `libsm`) when patching `aclocal.m4` was undone by the `autoreconf`.

**Comment by bw-yuhogg** [comment]
Hey @maxim-belkin the aclocal patch was still being used by `xtrans`, so that build currently fails with a 404 when downloading the patch.

Applying the configure patch instead seems to work.

**Comment by maxim-belkin** [comment]
Thanks for the heads up, @rwhogg . I forgot to commit xtrans. It should be fixed now.

**Comment by maxim-belkin** [comment]
For my own reference:
http://www.x.org/wiki/Development/Documentation/WritingDocumentation/
http://www.x.org/wiki/Development/Documentation/BuildingDocumentation/
Consider specifying `datarootdir`  / `docdir`
Consider making `xorg-sgml-doctools` required for documentation.
Consider using `build.with?("docs") or build.with?("specs")` everywhere

``` ruby

"#{Formula["xorg-sgml-doctools"].cellar}/share/doc/"

  --bindir=DIR            user executables [EPREFIX/bin]
  --sbindir=DIR           system admin executables [EPREFIX/sbin]
  --libexecdir=DIR        program executables [EPREFIX/libexec]
  --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
  --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --libdir=DIR            object code libraries [EPREFIX/lib]
  --includedir=DIR        C header files [PREFIX/include]
  --oldincludedir=DIR     C header files for non-gcc [/usr/include]
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
  --infodir=DIR           info documentation [DATAROOTDIR/info]
  --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
  --mandir=DIR            man documentation [DATAROOTDIR/man]
  --docdir=DIR            documentation root [DATAROOTDIR/doc/libXi]
  --htmldir=DIR           html documentation [DOCDIR]
  --dvidir=DIR            dvi documentation [DOCDIR]
  --pdfdir=DIR            pdf documentation [DOCDIR]
  --psdir=DIR             ps documentation [DOCDIR]
```

**Comment by sjackman** [comment]
@maxim-belkin Have you considered removing options from Linuxbrew/xorg? It would simplify the formulae.

**Comment by maxim-belkin** [comment]
Yes, I've considered this for `mesa`but not for smaller formulae - they do not bother me much and current issues are not related to options.
