### ISSUE TITLE
could not install libxt: "No package 'x11' found"

### ISSUE THREAD

**Issue by bw-yuhogg** [maxim-belkin/homebrew-xorg#219]
_From @ccshao on October 4, 2016 15:43_

If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
## Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

Please replace this line with a brief summary of your issue.

Could not install R in opensuse leap 42.1. 

```bash
checking for XT... configure: error: Package requirements (sm ice x11 xproto kbproto) were not met:
No package 'x11' found
in
./configure --prefix=/home/XXX/.linuxbrew/Cellar/libxt/1.1.5 

brew config
HOMEBREW_VERSION: 1.0.3-2-g3188f0d
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 3188f0dcdb07194ad345fabdaf8d02aaf6d6d02d
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: e17d71e861f1929820eb247ef6071e4bc76adf50
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /home/XXX/.linuxbrew
HOMEBREW_REPOSITORY: /home/XXX/.linuxbrew
HOMEBREW_CELLAR: /home/XXX/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 16-core 64-bit haswell
Homebrew Ruby: 2.1.2 => /usr/bin/ruby.ruby2.1
Clang: N/A
Git: 2.6.6 => /usr/bin/X11/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby.ruby2.1
Java: openjdk version "1.8.0_101"
Kernel: Linux 4.1.31-30-default x86_64 GNU/Linux
OS: openSUSE Leap 42.1 (x86_64)
Codename: n/a
OS glibc: 2.19
OS gcc: 4.8.5
Linuxbrew glibc: N/A
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A
```

_Copied from original issue: Linuxbrew/brew#126_

**Comment by bw-yuhogg** [comment]
That's pretty weird.  `linuxbrew/xorg/xorg` should have been installed as a dependency of R. The installation should work if you manually install it and then retry.

Also, can you please run `brew gist-logs r` and paste the result here please? Thanks a bunch!

**Comment by bw-yuhogg** [comment]
_From @ccshao on October 5, 2016 15:13_

full report of brew command

 `brew install r`
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing r from homebrew/science
==> Installing dependencies for homebrew/science/r: libxt, libxmu, libxml2, gettext, libxpm, libxaw, libxfixes, libxcomposite, libxrender, libxcursor, libxdamage, font-util, libfontenc, libpng, freetype, libxfont, libxft, libxi, libxinerama, libxrandr, libxres, libxtst, libxv, libxvmc, libxxf86dga, libxxf86vm, libdmx, libpciaccess, libxkbfile, libxshmfence, linuxbrew/xorg/xorg, texinfo, jpeg, libtiff, pcre, curl
==> Installing homebrew/science/r dependency: libxt
==> Downloading http://ftp.x.org/pub/individual/lib/libXt-1.1.5.tar.bz2
Already downloaded: /home/cshao/.cache/Homebrew/libxt-1.1.5.tar.bz2
==> Downloading https://raw.githubusercontent.com/Linuxbrew/homebrew-xorg/master/patch_configure.diff
Already downloaded: /home/cshao/.cache/Homebrew/libxt--patch-e3aff4be9c8a992fbcbd73fa9ea6202691dd0647f73d1974ace537f3795ba15f.diff
==> Patching
==> Applying patch_configure.diff
patching file configure
Hunk #1 succeeded at 18224 (offset -423 lines).
==> ./configure --prefix=/home/cshao/.linuxbrew/Cellar/libxt/1.1.5 --sysconfdir=/home/cshao/.linuxbrew/etc --localstatedir=/home/cshao/.linuxbrew/var --with-appdefaultdir=/home/cshao/.linuxbrew/etc/X11/app-
Last 15 lines from /home/cshao/.cache/Homebrew/Logs/libxt/01.configure:
checking for perl... /usr/bin/perl
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking for XT... configure: error: Package requirements (sm ice x11 xproto kbproto) were not met:

No package 'x11' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XT_CFLAGS
and XT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-xorg/issues

unfortunately,  brew gist-logs r gave me nothing
`brew gist-logs r`
Error: No logs.

**Comment by bw-yuhogg** [comment]
Ah, this is actually a problem with `libxt`. Moving to the linuxbrew/homebrew-xorg repo.

**Comment by bw-yuhogg** [comment]
`libxt` should install `libx11` as a dependency, but it doesn't appear to have done so.

Can you try `brew install -v libx11`, followed by `brew install -v libxt`?

**Comment by ccshao** [comment]
libx11 is installed:

> Warning: linuxbrew/xorg/libx11-1.6.3 already installed

`brew install -v libxt`

> checking for XT... configure: error: Package requirements (sm ice x11 xproto kbproto) were not met:
> 
> No package 'x11' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables XT_CFLAGS
> and XT_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> 
> Error: linuxbrew/xorg/libxt 1.1.5 did not build

**Comment by bw-yuhogg** [comment]
@maxim-belkin any ideas here? I tried to reproduce this on my home machine today, no luck.

@ccshao does `brew doctor` say anything?

**Comment by maxim-belkin** [comment]
@rwhogg : Install `xorg`, remove `libxt`, try to install `r`. 

``` bash
$ brew missing
linuxbrew/xorg/libxmu: libxt
linuxbrew/xorg/libxaw: libxt
linuxbrew/xorg/xorg: libxt

$ brew install r
.... [a few lines] ....
==> ./configure --prefix=/data/server4/mbelkin/.linuxbrew/Cellar/r/3.3.1_3 --with-libintl-prefix=/data/server4/mbel
Last 15 lines from /home/mbelkin/.cache/Homebrew/Logs/r/01.configure:
checking whether iswctype exists and is declared... yes
checking for wctrans_t... yes
checking for mbstate_t... yes
checking for ICU... no
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking X11/Intrinsic.h usability... yes
checking X11/Intrinsic.h presence... yes
checking for X11/Intrinsic.h... yes
checking for XtToolkitInitialize in -lXt... no
configure: error: --with-x=yes (default) and X11 headers/libs are not available
```

@ccshao, I need gist-logs to look at. Can't say much without them. `brew gist-logs libxt` and post the link here.

**Comment by ccshao** [comment]
@rwhogg here is the output of brew doctor:

```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/bin/X11/pkg-config
  /usr/bin/X11/x86_64-suse-linux-gnu-pkg-config
  /usr/bin/X11/isolinux-config
  /usr/bin/X11/python3-config
  /usr/bin/X11/python3.4-config
  /usr/bin/X11/python3.4m-config
  /usr/bin/X11/icu-config
  /usr/bin/X11/ncurses5-config
  /usr/bin/X11/ncurses6-config
  /usr/bin/X11/ncursesw5-config
  /usr/bin/X11/ncursesw6-config
  /usr/bin/X11/libart2-config
  /usr/bin/X11/python-config
  /usr/bin/X11/python2-config
  /usr/bin/X11/python2.7-config
  /usr/bin/X11/cups-config
  /usr/bin/X11/freetype-config
  /usr/bin/X11/brltty-config
  /usr/bin/X11/pcre-config
  /usr/bin/X11/antlr-config
  /usr/bin/X11/libpng16-config
  /usr/bin/X11/libpng-config

Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/cshao/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile
```

@maxim-belkin , `brew missing` gives no output.
The link of brew gist-logs libxt
https://gist.github.com/9405cbe7b0348f5854c873caeecfe287

Thanks!

**Comment by maxim-belkin** [comment]
@ccshao: clearly there are several problems with your setup. First and foremost, fix problems with `*-config` that were identified by `brew doctor`. Then, try installing `libxt` again and post new gist-logs here. I see a number of problems in gist-logs, but they might go away once you fix `brew doctor`'s problems

**Comment by ccshao** [comment]
@maxim-belkin The configs are made by opensuse itself, what should I with these configs?

**Comment by maxim-belkin** [comment]
get rid of `/usr/bin/X11` from your PATH...?

**Comment by ccshao** [comment]
@maxim-belkin I am not sure I want to remove the x11 from path, as opensuse might
use it on system level. I will do more search on it and let you know.

**Comment by ccshao** [comment]
@maxim-belkin I removed x11 from my path, still could not install R.
==> Installing homebrew/science/r dependency: libxt
==> Downloading http://ftp.x.org/pub/individual/lib/libXt-1.1.5.tar.bz2
Already downloaded: /home/cshao/.cache/Homebrew/libxt-1.1.5.tar.bz2
==> Downloading https://raw.githubusercontent.com/Linuxbrew/homebrew-xorg/master/p
Already downloaded: /home/cshao/.cache/Homebrew/libxt--patch-e3aff4be9c8a992fbcbd73fa9ea6202691dd0647f73d1974ace537f3795ba15f.diff
==> Patching
==> Applying patch_configure.diff
patching file configure
Hunk #1 succeeded at 18224 (offset -423 lines).
==> ./configure --prefix=/home/cshao/.linuxbrew/Cellar/libxt/1.1.5 --sysconfdir=/h
Last 15 lines from /home/cshao/.cache/Homebrew/Logs/libxt/01.configure:
checking for perl... /usr/bin/perl
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking for XT... configure: error: Package requirements (sm ice x11 xproto kbproto) were not met:

No package 'x11' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XT_CFLAGS
and XT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Should I set the PKG_CONFIG_PATH? and how?

**Comment by moozzz** [comment]
the problem starts even earlier. `libxt` depends on `libx11`. The latter is not properly linked due to, perhaps, a bug in the formula.

Solved this problem by:
1) installing all dependencies of `libxt` via `brew install`
2) going to $HOME/.linuxbrew/Cellar/libx11/1.6.3
3) manually linking everything in the `lib64` folder to $HOME/.linuxbrew/lib64

**Comment by bw-yuhogg** [comment]
@moozzz what files are contained in `$HOME/.linuxbrew/Cellar/libx11/1.6.3/lib64` and `$HOME/.linuxbrew/Cellar/libx11/1.6.3/lib`? `libx11` doesn't have a lib64 folder on my system.

Are you on an OpenSUSE system and/or a multiarch system? If this is distro-specific, the problem might happen to other formulae too and might require a `brew`-level fix.
