### ISSUE TITLE
How to link with -lGL

### ISSUE THREAD

**Issue by bw-yuhogg** [maxim-belkin/homebrew-xorg#22]
_From @vladfi1 on May 3, 2016 16:7_

I'm compiling an application with `-lGL`, and this predictably fails because brew's ld doesn't use `/usr/lib64`. However, I can't figure out how to get a brew-compatible `libGL.so`. I tried `brew install`ing a some packages such as `homebrew/x11/freeglut` and `glew`, to no avail. I even tried installing `homebrew/x11/mesalib-glw` but it failed with missing `-lGL` -  I would have expected this package to at least bring in the right dependencies that provide `libGL.so`. This makes me suspect that there is no way to link with `-lGL` outside of manually changing each `-lGL` to `/usr/lib64/libGL.so`, which I hear may cause problems.

_Copied from original issue: Linuxbrew/brew#14_

**Comment by rwhogg** [comment]
_From @sjackman on May 3, 2016 17:27_

This issue should probably be moved to https://github.com/Linuxbrew/homebrew-xorg
@rwhogg If you agree please move it.

**Comment by sjackman** [comment]
`libGL.so` is provided by [Mesa](http://www.mesa3d.org), which does not currently have a formula.

**Comment by vladfi1** [comment]
So the only solution is to give absolute paths to `GL` and `GLU`?

**Comment by bw-yuhogg** [comment]
Related to https://github.com/Linuxbrew/linuxbrew/issues/1027, where we were also discussing the possibility of packaging Mesa-related formulae.

**Comment by sjackman** [comment]
You can create a host keg. For example

``` sh
mkdir -p `brew --cellar`/libgl/1
ln -s /usr/lib64/libGL.so* `brew --cellar`/libgl/1
brew link libgl
```

**Comment by vladfi1** [comment]
@sjackman I followed your steps, but it didn't seem to do anything. The `brew link` step claimed that 0 symlinks were created, and `ld` still can't find `-lGL`.

**Comment by sjackman** [comment]
I had a mistake above. Sorry.

``` sh
mkdir -p `brew --cellar`/libgl/1/lib
ln -s /usr/lib64/libGL.so* `brew --cellar`/libgl/1/lib/
brew link libgl
```

**Comment by vladfi1** [comment]
Ok, that worked.

**Comment by sjackman** [comment]
Glad to hear it.
