### ISSUE TITLE
Upgrade wayland to 1.13.0

### ISSUE THREAD

**Issue by bw-yuhogg** [maxim-belkin/homebrew-xorg#251]
Make sure to read the release notes on this!

**Comment by maxim-belkin** [comment]
[here](https://lists.freedesktop.org/archives/wayland-devel/2016-September/031121.html)

**Comment by bw-yuhogg** [comment]
Edit: it's now at 1.13.0 and wayland-protocols also needs to be updated.

**Comment by maxim-belkin** [comment]
:/

**Comment by bw-yuhogg** [comment]
Fixed by #292
