### ISSUE TITLE
freeglut is in both core and xorg

### ISSUE THREAD

**Issue by bw-yuhogg** [maxim-belkin/homebrew-xorg#266]
This wasn't a problem when Homebrew's `freeglut` was in the x11 tap, but now core's `freeglut` will shadow xorg's.

**Comment by maxim-belkin** [comment]
darn! We have to test that the freeglut bottle that was built corresponds to our freeglut...

**Comment by maxim-belkin** [comment]
should we just remove it? I'd prefer to keep it but... it's hard to complete with homebrew/core

**Comment by bw-yuhogg** [comment]
My preference: migrate any necessary patches from your work on the xorg version over to core, delete the xorg version, and then add a tap migration from xorg->core.

This way, we can let upstream handle new versions.

(That said: I know very little about OpenGL and I'll trust your judgement if you disagree)

**Comment by maxim-belkin** [comment]
I agree. I don't want to have 2 gluts even if they are free. I'll see what was necessary to build a bottle -- I think "nothing" but, perhaps, will have to do something so that formula does exactly that.

**Comment by maxim-belkin** [comment]
I removed freeglut from xorg. Please add tap migration if you wish.
