### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by maxim-belkin** [maxim-belkin/homebrew-xorg#278]
Moving `linuxbrew/xorg`-related conversation from Homebrew/homebrew-science#5217 here.

@sjackman related to your [comment](https://github.com/Homebrew/homebrew-science/pull/5217#issuecomment-285150487): should we change all dependencies in this repo to `linuxbrew/xorg/<package>`?

**Comment by sjackman** [comment]
This looks to me to be a bug in `brew`, and I don't really understand it yet. I think we ought to understand it better first before making a big change. That being said, I don't think there's any harm to the change if you want to go ahead with it.

The `xorg` formula that are depended on directly in core are primarily:
```
linuxbrew/xorg/glu
linuxbrew/xorg/mesa
linuxbrew/xorg/xorg
```
and also for `libxkbcommon.rb`
```
linuxbrew/xorg/xkeyboardconfig
linuxbrew/xorg/libxcb
```
You may want to consider changing those. If you're going to change those ones though, you may just want to change all of them for consistency.

Now that I've rambled on a bit, I think the answer is, yes, change them all. Know that it may or may not resolve this issue with `homebrew/science/octave`. It's just a guess of mine really.

**Comment by maxim-belkin** [comment]
see Linuxbrew/homebrew-xorg#279
