### ISSUE TITLE
libxcb: configure script fails to find xproto required by libxau

### ISSUE THREAD

**Issue by fusion809** [maxim-belkin/homebrew-xorg#362]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? `brew doctor` gives `Your system is ready to brew`.

### Bug reports:
[Here](https://gist.github.com/0dba5c967141313cd8d4e220ec685907) is the gist of the output I get from `brew install octave`. Wondering if this error belongs here or elsewhere, but given that the precise error involves a Xorg dependency. 

The precise error is:

```bash
==> ./configure --prefix=/home/fusion809/.linuxbrew/Cellar/libxcb/1.12_2 --sysconfdir=/home/fusion809/.linuxbrew/etc --localstatedir=/home/fusion809/.linuxbrew/var --enable-xevie --enable-xinput --enable-xprint --disable-silent-rules --enable-static=no --enable-devel-docs=no --with-doxygen=no
Last 15 lines from /home/fusion809/.cache/Homebrew/Logs/libxcb/01.configure:
configure: WARNING: dot not found - doxygen targets will be skipped
checking for CHECK... yes
checking for xsltproc... no
checking for XCBPROTO... yes
checking for NEEDED... no
configure: error: Package requirements (pthread-stubs xau >= 0.99.2) were not met:

Package 'xproto', required by 'xau', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables NEEDED_CFLAGS
and NEEDED_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by maxim-belkin** [comment]
Thank you for the report.
Looks like it has been introduced by https://github.com/Linuxbrew/homebrew-xorg/commit/183bb471a284bdc879430be226678413cf99aee6 I will fix this soon

**Comment by maxim-belkin** [comment]
@fusion809, I pushed #363. Could you please verify that it fixes the issue for you:
```
brew update
brew install libxcb
```
?

**Comment by fusion809** [comment]
It is building properly now, thanks.
