### ISSUE TITLE
 xcb-proto wrong download URLs

### ISSUE THREAD

**Issue by cluck** [maxim-belkin/homebrew-xorg#376]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/15dce11548e10f020a1ac50255a47ddb
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? (it worked)

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

```
--- xcb-proto.rb.orig   2018-07-10 18:34:01.838263189 +0200
+++ xcb-proto.rb        2018-07-10 18:36:46.663736628 +0200
@@ -21,15 +21,15 @@
   patch :p1 do
     # March 16, 2018
     # http://www.linuxfromscratch.org/patches/blfs/8.2/xcb-proto-1.12-python3-1.patch
-    url "https://github.com/Linuxbrew/homebrew-xorg/master/Patches/xcb-proto-1.12-python3-1.patch"
-    sha256 "4eef0285392c525fcb7aeb54c1b6dc8406dc33c5845c1311b65b3efc409bea2e"
+    url "https://raw.githubusercontent.com/Linuxbrew/homebrew-xorg/master/Patches/xcb-proto-1.12-python3-1.patch"
+    sha256 "891645ea0453dca9b7f4a9c0886209c2c5a28638355912f969a36f9048c24070"
   end

   patch :p1 do
     # March 16, 2018
     # http://www.linuxfromscratch.org/patches/blfs/8.2/xcb-proto-1.12-schema-1.patch
-    url "https://github.com/Linuxbrew/homebrew-xorg/master/Patches/xcb-proto-1.12-schema-1.patch"
-    sha256 "3bc1a1871d17325d1f591a8ec2091f956b2071d83a6e9998d7d4880c4abf3e8b"
+    url "https://raw.githubusercontent.com/Linuxbrew/homebrew-xorg/master/Patches/xcb-proto-1.12-schema-1.patch"
+    sha256 "cee5134594c7d4739c96aa8b19712cb6a5776ec964d0f835561038581364df0c"
   end

```

**Comment by maxim-belkin** [comment]
Thanks for reporting this, @cluck!
