### ISSUE TITLE
mesa: GL/glxproto.h No such file or directory

### ISSUE THREAD

**Issue by Gwang-Jin** [maxim-belkin/homebrew-xorg#380]
Hello,

When I install `mesa` with current RB, I met new error in the process of `make check`
```
Last 15 lines from /home/skpark/.cache/Homebrew/Logs/mesa/05.make:
In file included from ../indirect_init.h:37:0,
                 from indirect_api.cpp:48:
../glxclient.h:52:25: fatal error: GL/glxproto.h: No such file or directory
compilation terminated.
make[5]: *** [indirect_api.o] Error 1
```
[https://gist.github.com/76016ef4067c44dd30f7f23452012bb8](https://gist.github.com/76016ef4067c44dd30f7f23452012bb8)

Thank you.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

**Comment by maxim-belkin** [comment]
Is this still an issue?

**Comment by behr328** [comment]
I'm seeing the same error.
