### ISSUE TITLE
SHA256 mismatch on the xorg-protocols formula

### ISSUE THREAD

**Issue by bw-yuhogg** [maxim-belkin/homebrew-xorg#4]
http://www.linuxfromscratch.org/blfs/view/svn/x/x7proto.html was changed yesterday, which means the SHA256 hash no longer matches.

The new SHA256 is 0d079c6821cc976dbde7adacf1d9625a92f0c7dea3c068a83ce13636af802ee5, but given that this page is basically an SVN head, I think it's wisest not to rely on a hash at all.

My proposed solution: just create a gist with a really small README and use that as the URL instead so we can have a non-empty installation.

**Comment by sjackman** [comment]
You could use
https://raw.githubusercontent.com/Linuxbrew/homebrew-xorg/master/README.md

**Comment by maxim-belkin** [comment]
Change in a web-page indicates updated package. In this case it was `videoproto`.
