### ISSUE TITLE
cannot install libX11 clang: error: no input files (xcode 10 issue?)

### ISSUE THREAD

**Issue by filefolder** [maxim-belkin/homebrew-xorg#549]
tried searching for this but couldn't find anything, so apologies in advance. i'm a linux user so i'm a bit lost what shims or clang are.

anyway here's the output of 'brew install libx11' (or xorg, or libxt, etc etc). 

edit/update: seems like this may be related to xcode version 10(.3). similar cpp issue here: https://github.com/Homebrew/brew/issues/5153

~~
==> ./configure --prefix=/usr/local/Cellar/libx11/1.6.8 --sysconfdir=/usr/local/etc --localstatedir=
Last 15 lines from /Users/Robert/Library/Logs/Homebrew/libx11/01.configure:
checking if clang supports -Werror=pointer-to-int-cast... yes
checking if clang supports -pedantic... yes
checking if clang supports -Werror... yes
checking if clang supports -Werror=attributes... yes
checking whether make supports nested variables... (cached) yes
checking whether to build functional specifications... no
checking for xmlto... no
configure: WARNING: xmlto not found - documentation targets will be skipped
checking for xsltproc... /usr/bin/xsltproc
checking for X.Org SGML entities >= 1.10... no
checking for cpp... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/cpp
checking if /usr/local/Homebrew/Library/Homebrew/shims/mac/super/cpp requires -undef... clang: error: no input files
clang: error: no input files
clang: error: no input files
configure: error: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/cpp defines unix with or without -undef.  I don't know what to do.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Linuxbrew/homebrew-xorg/issues

---
EDIT for anyone else stuck: easy workaround is just to extract the downloaded package and ./configure, make, make install the old fashioned way.

**Comment by maxim-belkin** [comment]
libx11 was migrated to Homebrew/linuxbrew-core
