### ISSUE TITLE
Cant build/install libx11

### ISSUE THREAD

**Issue by juliocpmelo** [maxim-belkin/homebrew-xorg#566]
I was trying to install libx11 in order to get some other lib working and got the error below. A workaround would work fine for me.

Install command
brew install libx11

Brew version
Homebrew 2.1.15-63-g090259b

Gist log
https://gist.github.com/51f300f059f69755ff76c7838f64f175

Build error seems to be related to libX11 version or something, it is missing some .h files tha are supposed to be in the X11/extensions. there goes the error output:

XKBGeom.c:36:36: fatal error: X11/extensions/XKBgeom.h: No such file or directory
compilation terminated.
Makefile:519: recipe for target 'XKBGeom.lo' failed
make[3]: *** [XKBGeom.lo] Error 1
make[3]: Leaving directory '/tmp/libx11-20191025-32396-zqn5w2/libX11-1.6.8/src/xkb'
Makefile:1262: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/libx11-20191025-32396-zqn5w2/libX11-1.6.8/src'
Makefile:820: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/libx11-20191025-32396-zqn5w2/libX11-1.6.8/src'
Makefile:521: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by czhu** [comment]
same issue I got today.

**Comment by maxim-belkin** [comment]
Thank you, Julio, for the report and Chenchen for confirming this. I confirm this build failure.
This is most likely caused by the updated version of `xorgproto` package. I'll look into this.

**Comment by maxim-belkin** [comment]
Yes, `libx11` 1.6.8 requires `X11/extensions/XKBgeom.h` which is provided by `xorgproto` 2019.2 only when compiled with `--enable-legacy` option

**Comment by maxim-belkin** [comment]
OK, to fix `libx11` 1.6.8 I would have to add `--enable-legacy` flag to `xorgproto`. However, `libx11` 1.6.9 builds fine without this option. So, I'm going to update `libx11` to 1.6.9 and add an option to build xorgproto with `--enable-legacy` flag when needed.

**Comment by maxim-belkin** [comment]
Updating `libx11` here: https://github.com/Linuxbrew/homebrew-xorg/pull/567

**Comment by maxim-belkin** [comment]
`--enable-legacy` flag added in ac6a8dc

**Comment by maxim-belkin** [comment]
I merged #567 in, so `libx11` should compile again. I also added `--with-legacy-headers` option to `xorgproto` so _if_ you still encounter the error above (or if you need legacy headers) -- build `xorgproto` from source with `--with-legacy-headers` option.

May I close this issue, @juliocpmelo and @czhu?

**Comment by juliocpmelo** [comment]
Hello @maxim-belkin, it works fine now. Thanks!

**Comment by czhu** [comment]
works perfectly now. Thanks!
