### ISSUE TITLE
Making formulae linuxbrew/core-ready

### ISSUE THREAD

**Issue by maxim-belkin** [maxim-belkin/homebrew-xorg#628]
```bash
cd $(brew --repo homebrew/core)/Formula
grep -ho 'linuxbrew/xorg/[^"]*' * | sort -u | sed 's/linuxbrew\/xorg\//- [ ] /'
```

- [ ] glu
- [ ] libdrm
- [ ] libice
- [x] libpthread-stubs
- [x] libsm<sup>* uses xmlto patch</sup>
- [x] libx11
- [ ] libxaw
- [x] libxcb #664
- [ ] libxcomposite
- [ ] libxcursor
- [ ] libxdamage
- [ ] libxext
- [ ] libxfixes
- [ ] libxft
- [ ] libxinerama
- [ ] libxmu
- [ ] libxpm
- [ ] libxrandr
- [ ] libxrender
- [ ] libxscrnsaver
- [ ] libxt
- [ ] libxtst
- [ ] libxv
- [ ] libxxf86vm
- [x] ~mesa~ #647
- [ ] wayland
- [ ] wayland-protocols
- [ ] xbitmaps
- [ ] xcb-util
- [ ] xcb-util-image
- [ ] xcb-util-keysyms
- [ ] xcb-util-renderutil
- [ ] xcb-util-wm
- [x] xinput (no PR, direct push)
- [x] xkeyboardconfig - #629
- [ ] xorg
- [ ] xorgproto

**Comment by iMichka** [comment]
Closing here as everything that needed to be migrated got migrated.
