### ISSUE TITLE
build stopped: subcommand failed

### ISSUE THREAD

**Issue by webtoolsde** [maxim-belkin/homebrew-xorg#635]
[892/2369] Compiling C++ object 'src/amd/compiler/src@amd@compiler@@aco@sta/aco_ssa_elimination.cpp.o'.
[893/2369] Compiling C object 'src/mesa/src@mesa@@mesa_classic@sta/vbo_vbo_exec_api.c.o'.
[894/2369] Generating sid_tables_h with a meson_exe.py custom command.
[895/2369] Compiling C object 'src/mesa/src@mesa@@mesa_classic@sta/main_format_utils.c.o'.
[896/2369] Compiling C object 'src/intel/perf/src@intel@perf@@intel_perf@sta/meson-generated_.._gen_perf_metrics.c.o'.
[897/2369] Compiling C object 'src/mesa/src@mesa@@mesa_classic@sta/meson-generated_.._.._mapi_glapi_gen_marshal_generated.c.o'.
ninja: build stopped: subcommand failed.

Environment Linux (Debian 10) 

Is there a need for root access? It is a managed server and so this is a problem then.

**Comment by maxim-belkin** [comment]
@Harald68, I'd need to see build logs (`brew gist-logs linuxbrew/xorg/mesa`) to comment on the issue.

**Comment by hariharan-durai** [comment]
Facing the same issue.
Environment Ubuntu 16.

Installing vips dependency: linuxbrew/xorg/mesa
==> Patching
==> Applying mesa-add_xdemos-1.patch
patching file src/glx/meson.build
Hunk #1 succeeded at 169 (offset 3 lines).
patching file src/glx/xdemos/glinfo_common.c
patching file src/glx/xdemos/glinfo_common.h
patching file src/glx/xdemos/glxgears.1
patching file src/glx/xdemos/glxgears.c
patching file src/glx/xdemos/glxinfo.1
patching file src/glx/xdemos/glxinfo.c
patching file src/glx/xdemos/meson.build
==> python3 -c import setuptools... --no-user-cfg install --prefix=/home/messiah/.linuxbrew/Cellar/mesa/19.3.3/libexec/vendor --install-scripts=/home/messiah/.linuxbrew/Cellar/mesa/19.3.3/libexec/vend
==> meson -Dprefix=/home/messiah/.linuxbrew/Cellar/mesa/19.3.3 -Dsysconfdir=/home/messiah/.linuxbrew/etc -Dlocalstatedir=/home/messiah/.linuxbrew/var -Dllvm=true -Dshared-llvm=false -Dplatforms=x11,
==> ninja




Last 15 lines from /home/messiah/.cache/Homebrew/Logs/mesa/03.ninja:
g++-5 -Isrc/amd/llvm/src@amd@llvm@@amd_common_llvm@sta -Isrc/amd/llvm -I../src/amd/llvm -Iinclude -I../include -Isrc -I../src -Isrc/mapi -I../src/mapi -Isrc/mesa -I../src/mesa -I../src/gallium/include -Isrc/gallium/auxiliary -I../src/gallium/auxiliary -Isrc/compiler -I../src/compiler -Isrc/amd -I../src/amd -Isrc/amd/common -I../src/amd/common -Isrc/compiler/nir -I../src/compiler/nir -I/home/messiah/.linuxbrew/Cellar/llvm/10.0.0_7/include -I/home/messiah/.linuxbrew/Cellar/libelf/0.8.13_1/include/libelf -I/home/messiah/.linuxbrew/Cellar/libelf/0.8.13_1/include -I/home/messiah/.linuxbrew/Cellar/libdrm/2.4.100/include -I/home/messiah/.linuxbrew/Cellar/libdrm/2.4.100/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O2 -g '-DPACKAGE_VERSION="19.3.3"' '-DPACKAGE_BUGREPORT="https://gitlab.freedesktop.org/mesa/mesa/issues"' -DUSE_ELF_TLS -DHAVE_ST_VDPAU -DENABLE_ST_OMX_BELLAGIO=0 -DENABLE_ST_OMX_TIZONIA=0 -DHAVE_X11_PLATFORM -DGLX_INDIRECT_RENDERING -DGLX_DIRECT_RENDERING -DGLX_USE_DRM -DHAVE_DRM_PLATFORM -DHAVE_SURFACELESS_PLATFORM -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUNC_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC_ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUTE_PACKED -DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -DHAVE_UINT128 -DUSE_SSE41 -DUSE_GCC_ATOMIC_BUILTINS -DUSE_X86_64_ASM -DMAJOR_IN_SYSMACROS -DHAVE_XLOCALE_H -DHAVE_SYS_SYSCTL_H -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_EXECINFO_H -DHAVE_SYS_SHM_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_TIMESPEC_GET -DHAVE_RANDOM_R -DHAVE_FLOCK -DHAVE_PROGRAM_INVOCATION_NAME -DHAVE_POSIX_MEMALIGN -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -DHAVE_PTHREAD -DHAVE_PTHREAD_SETAFFINITY -DHAVE_LIBDRM -DLLVM_AVAILABLE '-DMESA_LLVM_VERSION_STRING="10.0.0"' -DHAVE_WAYLAND_PLATFORM -DWL_HIDE_DEPRECATED -DHAVE_DRI3 -DHAVE_DRI3_MODIFIERS -DHAVE_LIBSENSORS=1 -Werror=return-type -Werror=empty-body -Wno-non-virtual-dtor -Wno-missing-field-initializers -fno-math-errno -fno-trapping-math -Werror=format -Wformat-security -fPIC -pthread -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -D_GNU_SOURCE -D__STDC_FORMAT_MACROS -fvisibility=hidden  -MD -MQ 'src/amd/llvm/src@amd@llvm@@amd_common_llvm@sta/ac_llvm_helper.cpp.o' -MF 'src/amd/llvm/src@amd@llvm@@amd_common_llvm@sta/ac_llvm_helper.cpp.o.d' -o 'src/amd/llvm/src@amd@llvm@@amd_common_llvm@sta/ac_llvm_helper.cpp.o' -c ../src/amd/llvm/ac_llvm_helper.cpp
../src/amd/llvm/ac_llvm_helper.cpp: In function 'ac_compiler_passes* ac_create_llvm_passes(LLVMTargetMachineRef)':
../src/amd/llvm/ac_llvm_helper.cpp:195:9: error: 'CGFT_ObjectFile' is not a member of 'llvm::TargetMachine'
         llvm::TargetMachine::CGFT_ObjectFile)) {
         ^
[737/2369] Compiling C++ object 'src/amd/compiler/src@amd@compiler@@aco@sta/aco_ssa_elimination.cpp.o'.
[738/2369] Compiling C++ object 'src/amd/compiler/src@amd@compiler@@aco@sta/aco_lower_to_cssa.cpp.o'.
[739/2369] Compiling C++ object 'src/amd/compiler/src@amd@compiler@@aco@sta/aco_interface.cpp.o'.
[740/2369] Compiling C++ object 'src/amd/compiler/src@amd@compiler@@aco@sta/aco_instruction_selection_setup.cpp.o'.
[741/2369] Compiling C++ object 'src/amd/compiler/src@amd@compiler@@aco@sta/aco_spill.cpp.o'.
[742/2369] Generating sid_tables_h with a meson_exe.py custom command.
[743/2369] Compiling C object 'src/intel/perf/src@intel@perf@@intel_perf@sta/meson-generated_.._gen_perf_metrics.c.o'.
[744/2369] Compiling C++ object 'src/amd/compiler/src@amd@compiler@@aco@sta/aco_instruction_selection.cpp.o'.
[745/2369] Compiling C object 'src/mesa/src@mesa@@mesa_classic@sta/meson-generated_.._.._mapi_glapi_gen_marshal_generated.c.o'.
ninja: build stopped: subcommand failed.

**Comment by maxim-belkin** [comment]
No response. Closing.
