### ISSUE TITLE
brew command return warning messages about xorg packages

### ISSUE THREAD

**Issue by zrma** [maxim-belkin/homebrew-xorg#697]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

#### my brew doctor result
<details>
  <summary>Command output</summary>
  <pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/zrma/.pyenv/shims/python-config
  /home/zrma/.pyenv/shims/python3-config
  /home/zrma/.pyenv/shims/python3.9-config
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libice instead of deprecated linuxbrew/xorg/libice
Warning: Use libsm instead of deprecated linuxbrew/xorg/libsm
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use libpciaccess instead of deprecated linuxbrew/xorg/libpciaccess
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libpciaccess instead of deprecated linuxbrew/xorg/libpciaccess
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libpciaccess instead of deprecated linuxbrew/xorg/libpciaccess
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use libxdamage instead of deprecated linuxbrew/xorg/libxdamage
Warning: Use libxrandr instead of deprecated linuxbrew/xorg/libxrandr
Warning: Use libxvmc instead of deprecated linuxbrew/xorg/libxvmc
Warning: Use libxxf86vm instead of deprecated linuxbrew/xorg/libxxf86vm
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libxrandr instead of deprecated linuxbrew/xorg/libxrandr
Warning: Use libice instead of deprecated linuxbrew/xorg/libice
Warning: Use libsm instead of deprecated linuxbrew/xorg/libsm
Warning: Use libxt instead of deprecated linuxbrew/xorg/libxt
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use libxi instead of deprecated linuxbrew/xorg/libxi
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libxinerama instead of deprecated linuxbrew/xorg/libxinerama
Warning: Use libxfixes instead of deprecated linuxbrew/xorg/libxfixes
Warning: Use libxdamage instead of deprecated linuxbrew/xorg/libxdamage
Warning: Use libxrandr instead of deprecated linuxbrew/xorg/libxrandr
Warning: Use libpciaccess instead of deprecated linuxbrew/xorg/libpciaccess
Warning: Use libxvmc instead of deprecated linuxbrew/xorg/libxvmc
Warning: Use libxxf86vm instead of deprecated linuxbrew/xorg/libxxf86vm
Warning: Use libice instead of deprecated linuxbrew/xorg/libice
Warning: Use libsm instead of deprecated linuxbrew/xorg/libsm
Warning: Use libpthread-stubs instead of deprecated linuxbrew/xorg/libpthread-stubs
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
Warning: Use libxau instead of deprecated linuxbrew/xorg/libxau
Warning: Use libx11 instead of deprecated linuxbrew/xorg/libx11
Warning: Use libxext instead of deprecated linuxbrew/xorg/libxext
Warning: Use libpciaccess instead of deprecated linuxbrew/xorg/libpciaccess
Warning: Use xorgproto instead of deprecated linuxbrew/xorg/xorgproto
  </pre>
</details>

----

recently brew command returns like that warning messages.

I use ubuntu 20.04 on WSL2 windows10 2004 and I tried to install xorg `sudo apt install xorg` or uninstall that.
but the message doesn't be changed.

how can I handle it?
thank you.

**Comment by maxim-belkin** [comment]
@iMichka, since you did this transition -- could you please take a look at this and suggest a solution?

**Comment by iMichka** [comment]
Yes, I know about the issue. And I know of to fix it.

Just to remember that this is a warning, so nothing should be broken.

This code checks for mentions of xorg formulae in your installed packages:
```
for tab in $(grep -l -o 'linuxbrew/xorg' $(brew --cellar)/*/*/INSTALL_RECEIPT.json)
do
  formula=$(basename $(dirname $(dirname $tab)))
  echo $formula
done
```

All these formulae need to be revision bumped. I did it once, but I think it did not work as expected. I need to check because I think homebrew-core was maybe not at the latest version when I did the rebuild with the new CI workflow in the xorg repo.

Anyway, as I still need to migrate a few xorg formulae to core, I'll do the final cleanup at the end.

**Comment by zrma** [comment]
thank you for your checking 😺

**Comment by iMichka** [comment]
Ok so all the formulae were migrated.

Regarding the warnings: make sure you `brew uninstall xorg` first.
Then run:

```
for tab in $(grep -l -o 'linuxbrew/xorg' $(brew --cellar)/*/*/INSTALL_RECEIPT.json)
do
    formula=$(basename $(dirname $(dirname $tab)))
    echo $formula
done
```

This will give you a list of formulae that need to be uninstalled and reinstalled.
Run  `brew uninstall --force` on each of these, and then `brew install`.

If at the end you still have issues, let me know, so that we can have a look.

**Comment by zrma** [comment]
> Ok so all the formulae were migrated.
> 
> Regarding the warnings: make sure you `brew uninstall xorg` first.
> Then run:
> 
> ```
> for tab in $(grep -l -o 'linuxbrew/xorg' $(brew --cellar)/*/*/INSTALL_RECEIPT.json)
> do
>     formula=$(basename $(dirname $(dirname $tab)))
>     echo $formula
> done
> ```
> 
> This will give you a list of formulae that need to be uninstalled and reinstalled.
> Run `brew uninstall --force` on each of these, and then `brew install`.
> 
> If at the end you still have issues, let me know, so that we can have a look.

It works well!
thank you for your help 😺
