### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by sjackman** [maxim-belkin/homebrew-xorg#7]
Thanks for working on this, @maxim-belkin and @rwhogg. Maxim, Bob, how would you prefer to collaborate, using pull requests through Maxim, or both having committer rights?

**Comment by maxim-belkin** [comment]
I think development of `linuxbrew/homebrew-xorg` will speed up if Bob can commit too because (just like everyone) sometimes I have too many things to do and no time is left for Linuxbrew(xorg).

**Comment by sjackman** [comment]
Great. Bob, would you like to join the team?

**Comment by bw-yuhogg** [comment]
I would be honoured :)

**Comment by sjackman** [comment]
Excellent! Done. Happy committing!
