### ISSUE TITLE
Problems installing Deno in Netlify

### ISSUE THREAD

**Issue by oscarotero** [maxim-belkin/homebrew-xorg#716]
Hi.
Netlify is starting to use the linux version of homebrew to install tools as an experimental alpha feature. You can see more info here:
https://community.netlify.com/t/now-in-experimental-alpha-homebrew-access-in-the-build-image/26074

I want to install Deno but I'm getting the following error: https://community.netlify.com/t/support-for-deno-on-netlify/14172/14

The interesting part of the output is:

```
2:35:00 PM: linuxbrew/xorg/libva-internal was deleted from linuxbrew/xorg in commit 6fffa4a:
```

And this is how I found this commit: https://github.com/Linuxbrew/homebrew-xorg/commit/6fffa4a883987435a47e97c217d3feb7e1416e79

Not sure if this is an issue of linuxbrew (that need to update Deno formula) or is in the side of Netlify.
Thanks!

**Comment by maxim-belkin** [comment]
Hi Oscar, thanks for the report. Please use `libva` formula instead of `linuxbrew/xorg/libva-internal`.

**Comment by oscarotero** [comment]
Hi, @maxim-belkin 

Thanks for your reply, but I'm not sure if I can do this, because this is a feature of Netlify. I only can create a Brewfile with the packages I want to install (https://github.com/lumeland/base-blog/blob/master/Brewfile.netlify) but the problem is that `linuxbrew/xorg/libva-internal` is a dependency of Deno.

**Comment by jonchang** [comment]
> the problem is that linuxbrew/xorg/libva-internal is a dependency of Deno.

It is not. These were removed a week ago as you already pointed out. In any case, `deno` won't build or run on Linux due to its dependency on Python 2: https://formulae.brew.sh/formula/deno

Please get support from Netlify instead since their experimental feature seems to be broken.

**Comment by oscarotero** [comment]
Okay, thanks for the info.
