### ISSUE TITLE
The tap no longer works with Homebrew (3.4.2)

### ISSUE THREAD

**Issue by nirvdrum** [maxim-belkin/homebrew-xorg#720]
# Please follow the general troubleshooting steps first:

- [ X] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I blew away my Homebrew installation and started from scratch to avoid any compatibility issues due to stale files.

### Bug reports:

This tap uses some functionality that has been remove from Homebrew with no suitable replacement. 

```
> brew --version
Homebrew 3.4.2
Homebrew/homebrew-core (git revision c746b78fada; last commit 2022-03-16)
```

```
> brew tap linuxbrew/xorg
==> Tapping linuxbrew/xorg
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg'...
remote: Enumerating objects: 7884, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 7884 (delta 76), reused 17 (delta 9), pack-reused 7777
Receiving objects: 100% (7884/7884), 1.31 MiB | 7.83 MiB/s, done.
Resolving deltas: 100% (6120/6120), done.
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorg-fonts.rb
xorg-fonts: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the linuxbrew/xorg tap (not Homebrew/brew or Homebrew/core):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorg-fonts.rb:15

Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorg-apps.rb
xorg-apps: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the linuxbrew/xorg tap (not Homebrew/brew or Homebrew/core):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorg-apps.rb:15

Error: Cannot tap linuxbrew/xorg: invalid syntax in tap!
```

**Comment by maxim-belkin** [comment]
Hi Kevin! Thanks for the report! Yes, I haven't had a chance to work on this tap in some time, but I believe that all mission critical formulas have been migrated to the main core tap. I will have to see what to do about those "bottle :unneeded" issues because the way X.Org works does not map well into Homebrew's assumptions/requirements.

**Comment by maxim-belkin** [comment]
I had to remove "bottle :unneeded" lines from xorg-apps and xorg-fonts to make this tap "tappable". The next item that needs fixing is CI.

**Comment by jonchang** [comment]
Hey Maxim, if you need help with CI let me know. I recently fixed the CI of brewsci/bio, so you can use that as a model if it makes sense for this tap.

**Comment by maxim-belkin** [comment]
Hey, Jonathan! Yes, I would appreciate any help with the CI!

> so you can use that as a model if it makes sense for this tap.

Honestly, I am not sure but I vaguely recall @sjackman or you saying that brewsci/bio's CI is rather complex and other taps probably don't need that complexity. I see that `brew tap-new` generates two CI files, whereas brewsci/bio has more. I was going to work on modifying the files that `brew tap-new` generates (e.g., install `xvfb`, set "DISPLAY" env. var., use `xvfb-run`), but haven't had a chance to work on that yet.

**Comment by maxim-belkin** [comment]
@jonchang, I would appreciate your help with this. I looked at brewsci/bio's actions and they don't look too complicated. If you're still up to it, I'd appreciate a PR. Or we can do this over a Zoom/Slack call.

**Comment by jonchang** [comment]
Totally forgot about this! I'll try to get some work done on this in a draft PR sometime this week.

**Comment by maxim-belkin** [comment]
@jonchang, have you had a chance to look into this? Are there any roadblocks? If there are, should I ping Shaun or somebody else?

**Comment by jonchang** [comment]
I believe this is now fixed with this series of pull requests:

* https://github.com/maxim-belkin/homebrew-xorg/pull/723
* https://github.com/maxim-belkin/homebrew-xorg/pull/728

A maintainer on this repository can add a `CI-merge` label to any pull request with uploaded bottle artifacts. CI will automatically merge and close the associated issue.
