### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by sjackman** [maxim-belkin/homebrew-xorg#8]
Here's a few references:

https://github.com/Linuxbrew/linuxbrew/blob/master/.travis.yml
https://github.com/Homebrew/homebrew/blob/master/.travis.yml
https://github.com/Homebrew/homebrew-science/blob/master/.travis.yml

https://github.com/Linuxbrew/linuxbrew/blob/master/Dockerfile
https://github.com/Linuxbrew/linuxbrew/blob/master/docker.test.yml

**Comment by sjackman** [comment]
Anyone want to tackle setting up Travis?

**Comment by bw-yuhogg** [comment]
I helped homebrew-emacs set theirs up for Linux a few months ago. I can't get to this immediately, but I'll probably be able to take a look at this next weekend.

**Comment by sjackman** [comment]
Great! If it helps, there's a Docker image that I put together at [linuxbrew/linuxbrew](https://hub.docker.com/r/linuxbrew/linuxbrew).

**Comment by bw-yuhogg** [comment]
Fixed by #13
